name: Aveu Component library
on:
    push:
        branches: [master]
    pull_request:
        branches: [master]
jobs:
    react-app-workflow:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 14.x
              uses: actions/setup-node@v2
              with:
                  node-version: 14.x
            - name: tsc
              run: yarn tsc
            - name: run prettier
              run: yarn --prettier --write .
            - name: run eslint
              run: yarn eslint --fix
            - name: run test
              run: yarn test
